### ISSUE TITLE
Trojan found?

### ISSUE THREAD

**Issue by d3epone** [nicehash/nheqminer#201]
Downloaded nheqminer_v0.3b.zip on my Mac and tried to email it to my Windows machine.

My email has anti-virus scanning and refused to sent it throwing up the following :

127.0.0.1 [18616] >>drweb.tmp.0kli0J/4.part/nheqminer.exe infected with Trojan.BtcMine.1052

Is this a false alarm?

**Comment by S74nk0** [comment]
Hi @d3epone. If you have downloaded from the GitHub [releases](https://github.com/nicehash/nheqminer/releases) then yes this is a **false** positive. This is **open source** software so everyone can take it and repackage it (legitimately or incorporate it into malware), so make sure to build it yourself or **download from the [official releases](https://github.com/nicehash/nheqminer/releases)**. Some AV software flags mining software because of the fact that there are people that incorporate it into their malware and since the sources for the mining part are same it flags it because AV detects same binary patterns (a quick crude explanation how AV software works). So this is most likely a false positive. And of course always download binaries from their official sources, and you should be safe.

**Comment by d3epone** [comment]
Ahh cool, I guessed that was the case. Thanks bro.
