### ISSUE TITLE
Possible to use this as a static library?

### ISSUE THREAD

**Issue by bitbybitllc** [nicehash/nheqminer#206]
I'm curious if I can embed this in another program without dropping so many files to disk.

Right now I've embedded the miner and associated DLL's as resources in a C++ project and write them all out to disk and then use CreateProcess to launch nheqminer.exe.

Is there any more efficient way to accomplish what I'm trying to do?

**Comment by RiesenGurke123** [comment]
Do you want to programm your own mining botnet or for which reason would this be useful?

But you can build a library from the source of this project.

**Comment by basicsk8r13** [comment]
To be able to mine more than one alt coin without running several different processes. Working on a project that will mine the most profitable coin at that moment.

**Comment by RiesenGurke123** [comment]
I think you have to restructure the main function like this:

- remove commandline argument parsing
- make it like main(int num_threads, int num_hashes...)
- maybe rename main to something other
- move all the functions to a new namespace (sth. like ZcashMiner) for nameclash purposes

And then all you have to do is consult your compilers manual how to make this project a staticly linked library and rearange the build options to include all the source code into a single file.

Nobody in the nicehash team will do that for you, because they do not profit from it. But when you publish this static lib on github, there will be people thanking you.

**Comment by leggazoid** [comment]
I needed this for chromebook, modified CMakeList.txt as follows for xenoncat:

project(nheqminer_cpu_xenoncat)
cmake_minimum_required(VERSION 2.8)

#aux_source_directory(. SRC_LIST)
#add_executable(${PROJECT_NAME} ${SRC_LIST})

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

# LINUX
if(CMAKE_COMPILER_IS_GNUCXX)
    # use native cpu features
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=native")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++")
    # optimizations
    add_definitions(-O3)
endif()

# Common
include_directories(${nheqminer_SOURCE_DIR})

add_definitions(-DBOOST_ALL_NO_LIB)

set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME ON)

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
