### ISSUE TITLE
Visual C++ Compiler November 2013 CTP

### ISSUE THREAD

**Issue by pbuva** [nicehash/nheqminer#67]
After Visual Studio 2013 Community i cant install Visual C++ Compiler November 2013 CTP, because, any version of compiler is already in Visual Studio 2013 Community, i dont see this part in programs, any idea what to uninstall? Or, can you build new version for us with AMD? Thank you

**Comment by S74nk0** [comment]
If CTP cannot be installed it is probably due to **Microsoft Visual C++ 2013 Redistributable (x86/x64)** we had a similar problem and uninstalling that will let you install CTP compiler. This [link](https://github.com/nicehash/nheqminer/releases/download/0.3a/nheqminer_v0.3a.zip) has AMD support. But we will update sources soon.

**Comment by pbuva** [comment]
Thank you, v0.3a is currently better than full nicehash client (restarts), but AMD support is... Non-optimized :)

**Comment by S74nk0** [comment]
@pbuva we will update AMD solver with an optimized version.
